# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: proxy-ci

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ci.yaml'
      - 'src/**'
jobs:
  build:
    name: "deploy to test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Deploy Revision
      run: "curl --fail -X POST \"https://opdk.neram.net/platform/edu/proxies/my-guard-auth/overview/${{steps.upload.outputs.apigee-revision}}/deployments?override=true\""
